# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QGridLayout, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 898)
        MainWindow.setMinimumSize(QSize(900, 0))
        MainWindow.setMaximumSize(QSize(900, 16777215))
        self.actionManual = QAction(MainWindow)
        self.actionManual.setObjectName(u"actionManual")
        self.actionManual.setEnabled(False)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionPreferences.setEnabled(False)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(0, 90, 378, 16))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(370, -10, 16, 598))
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_15 = QFrame(self.centralwidget)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(0, 200, 378, 16))
        self.line_15.setFrameShape(QFrame.Shape.HLine)
        self.line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.KillAlarmLockButton = QPushButton(self.centralwidget)
        self.KillAlarmLockButton.setObjectName(u"KillAlarmLockButton")
        self.KillAlarmLockButton.setGeometry(QRect(270, 120, 81, 25))
        self.HomeButton = QPushButton(self.centralwidget)
        self.HomeButton.setObjectName(u"HomeButton")
        self.HomeButton.setGeometry(QRect(30, 120, 81, 25))
        self.ZeroPositionButton = QPushButton(self.centralwidget)
        self.ZeroPositionButton.setObjectName(u"ZeroPositionButton")
        self.ZeroPositionButton.setGeometry(QRect(150, 120, 81, 25))
        self.InverseKinematicsLabel = QLabel(self.centralwidget)
        self.InverseKinematicsLabel.setObjectName(u"InverseKinematicsLabel")
        self.InverseKinematicsLabel.setEnabled(False)
        self.InverseKinematicsLabel.setGeometry(QRect(90, 300, 201, 31))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        self.InverseKinematicsLabel.setFont(font)
        self.label_54 = QLabel(self.centralwidget)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(540, -7, 211, 31))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_54.setFont(font1)
        self.IkOutputValueFrame = QFrame(self.centralwidget)
        self.IkOutputValueFrame.setObjectName(u"IkOutputValueFrame")
        self.IkOutputValueFrame.setEnabled(False)
        self.IkOutputValueFrame.setGeometry(QRect(80, 560, 221, 21))
        self.IkOutputValueFrame.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.IkOutputValueFrame.setFrameShape(QFrame.Box)
        self.IkOutputValueFrame.setFrameShadow(QFrame.Plain)
        self.IkOutputValueZ = QLabel(self.IkOutputValueFrame)
        self.IkOutputValueZ.setObjectName(u"IkOutputValueZ")
        self.IkOutputValueZ.setGeometry(QRect(172, 2, 61, 16))
        self.IkOutputValueZ.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputY = QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputY.setObjectName(u"IkLabelOutputY")
        self.IkLabelOutputY.setGeometry(QRect(83, 0, 21, 20))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.IkLabelOutputY.setFont(font2)
        self.IkLabelOutputY.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkOutputValueX = QLabel(self.IkOutputValueFrame)
        self.IkOutputValueX.setObjectName(u"IkOutputValueX")
        self.IkOutputValueX.setGeometry(QRect(29, 2, 51, 16))
        self.IkOutputValueX.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputZ = QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputZ.setObjectName(u"IkLabelOutputZ")
        self.IkLabelOutputZ.setGeometry(QRect(153, 0, 21, 20))
        self.IkLabelOutputZ.setFont(font2)
        self.IkLabelOutputZ.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputX = QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputX.setObjectName(u"IkLabelOutputX")
        self.IkLabelOutputX.setGeometry(QRect(10, 0, 21, 20))
        self.IkLabelOutputX.setFont(font2)
        self.IkLabelOutputX.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkOutputValueY = QLabel(self.IkOutputValueFrame)
        self.IkOutputValueY.setObjectName(u"IkOutputValueY")
        self.IkOutputValueY.setGeometry(QRect(102, 2, 51, 16))
        self.IkOutputValueY.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.line_16 = QFrame(self.centralwidget)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(0, 580, 901, 16))
        self.line_16.setFrameShape(QFrame.Shape.HLine)
        self.line_16.setFrameShadow(QFrame.Shadow.Sunken)
        self.ConsoleInput = QLineEdit(self.centralwidget)
        self.ConsoleInput.setObjectName(u"ConsoleInput")
        self.ConsoleInput.setGeometry(QRect(40, 835, 711, 20))
        self.ConsoleButtonSend = QPushButton(self.centralwidget)
        self.ConsoleButtonSend.setObjectName(u"ConsoleButtonSend")
        self.ConsoleButtonSend.setGeometry(QRect(760, 835, 91, 23))
        self.ConsoleShowOkRespcheckBox = QCheckBox(self.centralwidget)
        self.ConsoleShowOkRespcheckBox.setObjectName(u"ConsoleShowOkRespcheckBox")
        self.ConsoleShowOkRespcheckBox.setGeometry(QRect(730, 615, 121, 17))
        self.ConsoleLabel = QLabel(self.centralwidget)
        self.ConsoleLabel.setObjectName(u"ConsoleLabel")
        self.ConsoleLabel.setGeometry(QRect(400, 600, 91, 31))
        self.ConsoleLabel.setFont(font1)
        self.ConsoleOutput = QPlainTextEdit(self.centralwidget)
        self.ConsoleOutput.setObjectName(u"ConsoleOutput")
        self.ConsoleOutput.setGeometry(QRect(40, 635, 811, 191))
        self.ConsoleOutput.setAcceptDrops(False)
        self.ConsoleOutput.setUndoRedoEnabled(False)
        self.ConsoleOutput.setReadOnly(True)
        self.line_17 = QFrame(self.centralwidget)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 290, 378, 16))
        self.line_17.setFrameShape(QFrame.Shape.HLine)
        self.line_17.setFrameShadow(QFrame.Shadow.Sunken)
        self.GripperFrame = QFrame(self.centralwidget)
        self.GripperFrame.setObjectName(u"GripperFrame")
        self.GripperFrame.setGeometry(QRect(0, 210, 371, 80))
        self.GripperFrame.setFrameShape(QFrame.StyledPanel)
        self.GripperFrame.setFrameShadow(QFrame.Raised)
        self.GripperLabel = QLabel(self.GripperFrame)
        self.GripperLabel.setObjectName(u"GripperLabel")
        self.GripperLabel.setGeometry(QRect(22, 10, 51, 20))
        self.GripperLabel.setFont(font2)
        self.Dec1ButtonGripper = QPushButton(self.GripperFrame)
        self.Dec1ButtonGripper.setObjectName(u"Dec1ButtonGripper")
        self.Dec1ButtonGripper.setGeometry(QRect(156, 50, 31, 23))
        self.Dec10ButtonGripper = QPushButton(self.GripperFrame)
        self.Dec10ButtonGripper.setObjectName(u"Dec10ButtonGripper")
        self.Dec10ButtonGripper.setGeometry(QRect(110, 50, 41, 23))
        self.SpinBoxGripper = QDoubleSpinBox(self.GripperFrame)
        self.SpinBoxGripper.setObjectName(u"SpinBoxGripper")
        self.SpinBoxGripper.setGeometry(QRect(20, 40, 51, 22))
        self.SpinBoxGripper.setAlignment(Qt.AlignCenter)
        self.SpinBoxGripper.setDecimals(0)
        self.SpinBoxGripper.setMinimum(0.000000000000000)
        self.SpinBoxGripper.setMaximum(100.000000000000000)
        self.Gripper0Label = QLabel(self.GripperFrame)
        self.Gripper0Label.setObjectName(u"Gripper0Label")
        self.Gripper0Label.setGeometry(QRect(110, 30, 16, 16))
        self.Gripper100Label = QLabel(self.GripperFrame)
        self.Gripper100Label.setObjectName(u"Gripper100Label")
        self.Gripper100Label.setGeometry(QRect(265, 30, 31, 16))
        self.Inc10ButtonGripper = QPushButton(self.GripperFrame)
        self.Inc10ButtonGripper.setObjectName(u"Inc10ButtonGripper")
        self.Inc10ButtonGripper.setGeometry(QRect(240, 50, 41, 23))
        self.Inc1ButtonGripper = QPushButton(self.GripperFrame)
        self.Inc1ButtonGripper.setObjectName(u"Inc1ButtonGripper")
        self.Inc1ButtonGripper.setGeometry(QRect(205, 50, 31, 23))
        self.SliderGripper = QSlider(self.GripperFrame)
        self.SliderGripper.setObjectName(u"SliderGripper")
        self.SliderGripper.setGeometry(QRect(110, 10, 171, 22))
        self.SliderGripper.setMinimum(0)
        self.SliderGripper.setMaximum(100)
        self.SliderGripper.setTracking(True)
        self.SliderGripper.setOrientation(Qt.Horizontal)
        self.SliderGripper.setInvertedAppearance(False)
        self.SliderGripper.setTickPosition(QSlider.TicksBelow)
        self.SliderGripper.setTickInterval(20)
        self.GoButtonGripper = QPushButton(self.GripperFrame)
        self.GoButtonGripper.setObjectName(u"GoButtonGripper")
        self.GoButtonGripper.setGeometry(QRect(320, 30, 35, 30))
        self.GoButtonGripper.setMinimumSize(QSize(35, 30))
        self.GoButtonGripper.setMaximumSize(QSize(35, 30))
        self.GoButtonGripper.setFont(font2)
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(36, 520, 321, 31))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.IKInputSpinBoxX = QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxX.setObjectName(u"IKInputSpinBoxX")
        self.IKInputSpinBoxX.setEnabled(False)
        self.IKInputSpinBoxX.setGeometry(QRect(15, 6, 82, 20))
        self.IKInputSpinBoxX.setAlignment(Qt.AlignCenter)
        self.IKInputSpinBoxX.setDecimals(2)
        self.IKInputSpinBoxX.setMinimum(-999.000000000000000)
        self.IKInputSpinBoxX.setMaximum(999.000000000000000)
        self.IKInputSpinBoxY = QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxY.setObjectName(u"IKInputSpinBoxY")
        self.IKInputSpinBoxY.setEnabled(False)
        self.IKInputSpinBoxY.setGeometry(QRect(125, 6, 82, 20))
        self.IKInputSpinBoxY.setAlignment(Qt.AlignCenter)
        self.IKInputSpinBoxY.setDecimals(2)
        self.IKInputSpinBoxY.setMinimum(-999.000000000000000)
        self.IKInputSpinBoxY.setMaximum(999.000000000000000)
        self.IkLabelInputY = QLabel(self.frame_4)
        self.IkLabelInputY.setObjectName(u"IkLabelInputY")
        self.IkLabelInputY.setEnabled(False)
        self.IkLabelInputY.setGeometry(QRect(110, 5, 14, 20))
        self.IkLabelInputY.setFont(font2)
        self.IkLabelInputY.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IkLabelInputX = QLabel(self.frame_4)
        self.IkLabelInputX.setObjectName(u"IkLabelInputX")
        self.IkLabelInputX.setEnabled(False)
        self.IkLabelInputX.setGeometry(QRect(0, 5, 14, 20))
        self.IkLabelInputX.setFont(font2)
        self.IkLabelInputX.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.IKInputSpinBoxZ = QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxZ.setObjectName(u"IKInputSpinBoxZ")
        self.IKInputSpinBoxZ.setEnabled(False)
        self.IKInputSpinBoxZ.setGeometry(QRect(233, 6, 82, 20))
        self.IKInputSpinBoxZ.setAlignment(Qt.AlignCenter)
        self.IKInputSpinBoxZ.setDecimals(2)
        self.IKInputSpinBoxZ.setMinimum(-999.000000000000000)
        self.IKInputSpinBoxZ.setMaximum(999.000000000000000)
        self.IkLabelInputZ = QLabel(self.frame_4)
        self.IkLabelInputZ.setObjectName(u"IkLabelInputZ")
        self.IkLabelInputZ.setEnabled(False)
        self.IkLabelInputZ.setGeometry(QRect(219, 5, 13, 20))
        self.IkLabelInputZ.setFont(font2)
        self.IkLabelInputZ.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.SerialPortLabel = QLabel(self.centralwidget)
        self.SerialPortLabel.setObjectName(u"SerialPortLabel")
        self.SerialPortLabel.setGeometry(QRect(20, 22, 65, 22))
        self.SerialPortLabel.setMinimumSize(QSize(65, 22))
        self.SerialPortLabel.setMaximumSize(QSize(65, 22))
        font3 = QFont()
        font3.setBold(True)
        self.SerialPortLabel.setFont(font3)
        self.RobotStateLabel = QLabel(self.centralwidget)
        self.RobotStateLabel.setObjectName(u"RobotStateLabel")
        self.RobotStateLabel.setGeometry(QRect(216, 22, 38, 22))
        self.RobotStateLabel.setMinimumSize(QSize(38, 22))
        self.RobotStateLabel.setMaximumSize(QSize(38, 22))
        self.RobotStateLabel.setFont(font3)
        self.SerialPortComboBox = QComboBox(self.centralwidget)
        self.SerialPortComboBox.setObjectName(u"SerialPortComboBox")
        self.SerialPortComboBox.setGeometry(QRect(91, 22, 80, 22))
        self.SerialPortComboBox.setMinimumSize(QSize(80, 22))
        self.SerialPortComboBox.setMaximumSize(QSize(80, 22))
        self.ConnectButton = QPushButton(self.centralwidget)
        self.ConnectButton.setObjectName(u"ConnectButton")
        self.ConnectButton.setGeometry(QRect(260, 50, 90, 23))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setMinimumSize(QSize(75, 22))
        self.ConnectButton.setMaximumSize(QSize(90, 25))
        self.ConnectButton.setFont(font3)
        self.ConnectButton.setLayoutDirection(Qt.LeftToRight)
        self.SerialPortRefreshButton = QPushButton(self.centralwidget)
        self.SerialPortRefreshButton.setObjectName(u"SerialPortRefreshButton")
        self.SerialPortRefreshButton.setGeometry(QRect(177, 22, 22, 22))
        self.SerialPortRefreshButton.setMinimumSize(QSize(22, 22))
        self.SerialPortRefreshButton.setMaximumSize(QSize(22, 22))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        self.SerialPortRefreshButton.setFont(font4)
        self.RobotStateDisplay = QLabel(self.centralwidget)
        self.RobotStateDisplay.setObjectName(u"RobotStateDisplay")
        self.RobotStateDisplay.setGeometry(QRect(260, 22, 90, 22))
        self.RobotStateDisplay.setMinimumSize(QSize(90, 22))
        self.RobotStateDisplay.setMaximumSize(QSize(90, 22))
        self.RobotStateDisplay.setFont(font3)
        self.RobotStateDisplay.setStyleSheet(u"background-color: rgb(255, 0, 0)")
        self.RobotStateDisplay.setFrameShape(QFrame.Box)
        self.RobotStateDisplay.setAlignment(Qt.AlignCenter)
        self.BaudRateComboBox = QComboBox(self.centralwidget)
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.setObjectName(u"BaudRateComboBox")
        self.BaudRateComboBox.setGeometry(QRect(91, 50, 80, 22))
        self.BaudRateComboBox.setMinimumSize(QSize(80, 22))
        self.BaudRateComboBox.setMaximumSize(QSize(80, 22))
        self.BaudRateLabel = QLabel(self.centralwidget)
        self.BaudRateLabel.setObjectName(u"BaudRateLabel")
        self.BaudRateLabel.setGeometry(QRect(20, 50, 65, 22))
        self.BaudRateLabel.setMinimumSize(QSize(65, 22))
        self.BaudRateLabel.setMaximumSize(QSize(65, 22))
        self.BaudRateLabel.setFont(font3)
        self.ConsoleShowVerbosecheckBox = QCheckBox(self.centralwidget)
        self.ConsoleShowVerbosecheckBox.setObjectName(u"ConsoleShowVerbosecheckBox")
        self.ConsoleShowVerbosecheckBox.setGeometry(QRect(580, 615, 131, 17))
        self.FKGoAllButton = QPushButton(self.centralwidget)
        self.FKGoAllButton.setObjectName(u"FKGoAllButton")
        self.FKGoAllButton.setGeometry(QRect(590, 520, 75, 30))
        self.FKGoAllButton.setMinimumSize(QSize(75, 30))
        self.FKGoAllButton.setMaximumSize(QSize(75, 30))
        self.FKGoAllButton.setFont(font2)
        self.FKOutputValueFrame = QFrame(self.centralwidget)
        self.FKOutputValueFrame.setObjectName(u"FKOutputValueFrame")
        self.FKOutputValueFrame.setGeometry(QRect(390, 560, 491, 21))
        self.FKOutputValueFrame.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.FKOutputValueFrame.setFrameShape(QFrame.Box)
        self.FKOutputValueFrame.setFrameShadow(QFrame.Plain)
        self.FKCurrentPosValueArt1 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt1.setObjectName(u"FKCurrentPosValueArt1")
        self.FKCurrentPosValueArt1.setGeometry(QRect(48, 2, 51, 16))
        self.FKCurrentPosValueArt1.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt1 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt1.setObjectName(u"FKLabelCurrentPosArt1")
        self.FKLabelCurrentPosArt1.setGeometry(QRect(10, 0, 41, 20))
        self.FKLabelCurrentPosArt1.setFont(font2)
        self.FKLabelCurrentPosArt1.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt2 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt2.setObjectName(u"FKLabelCurrentPosArt2")
        self.FKLabelCurrentPosArt2.setGeometry(QRect(90, 0, 41, 20))
        self.FKLabelCurrentPosArt2.setFont(font2)
        self.FKLabelCurrentPosArt2.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKCurrentPosValueArt2 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt2.setObjectName(u"FKCurrentPosValueArt2")
        self.FKCurrentPosValueArt2.setGeometry(QRect(128, 2, 51, 16))
        self.FKCurrentPosValueArt2.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt3 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt3.setObjectName(u"FKLabelCurrentPosArt3")
        self.FKLabelCurrentPosArt3.setGeometry(QRect(170, 0, 41, 20))
        self.FKLabelCurrentPosArt3.setFont(font2)
        self.FKLabelCurrentPosArt3.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKCurrentPosValueArt3 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt3.setObjectName(u"FKCurrentPosValueArt3")
        self.FKCurrentPosValueArt3.setGeometry(QRect(208, 2, 51, 16))
        self.FKCurrentPosValueArt3.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt4 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt4.setObjectName(u"FKLabelCurrentPosArt4")
        self.FKLabelCurrentPosArt4.setGeometry(QRect(250, 0, 41, 20))
        self.FKLabelCurrentPosArt4.setFont(font2)
        self.FKLabelCurrentPosArt4.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKCurrentPosValueArt4 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt4.setObjectName(u"FKCurrentPosValueArt4")
        self.FKCurrentPosValueArt4.setGeometry(QRect(288, 2, 51, 16))
        self.FKCurrentPosValueArt4.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt5 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt5.setObjectName(u"FKLabelCurrentPosArt5")
        self.FKLabelCurrentPosArt5.setGeometry(QRect(330, 0, 41, 20))
        self.FKLabelCurrentPosArt5.setFont(font2)
        self.FKLabelCurrentPosArt5.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKCurrentPosValueArt5 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt5.setObjectName(u"FKCurrentPosValueArt5")
        self.FKCurrentPosValueArt5.setGeometry(QRect(368, 2, 51, 16))
        self.FKCurrentPosValueArt5.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKCurrentPosValueArt6 = QLabel(self.FKOutputValueFrame)
        self.FKCurrentPosValueArt6.setObjectName(u"FKCurrentPosValueArt6")
        self.FKCurrentPosValueArt6.setGeometry(QRect(448, 2, 51, 16))
        self.FKCurrentPosValueArt6.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.FKLabelCurrentPosArt6 = QLabel(self.FKOutputValueFrame)
        self.FKLabelCurrentPosArt6.setObjectName(u"FKLabelCurrentPosArt6")
        self.FKLabelCurrentPosArt6.setGeometry(QRect(410, 0, 41, 20))
        self.FKLabelCurrentPosArt6.setFont(font2)
        self.FKLabelCurrentPosArt6.setStyleSheet(u"background-color: rgba(255, 255, 255,0)")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(390, 30, 491, 81))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_7 = QFrame(self.layoutWidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_29 = QLabel(self.frame_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(408, 24, 31, 16))
        self.FKLabelArt1 = QLabel(self.frame_7)
        self.FKLabelArt1.setObjectName(u"FKLabelArt1")
        self.FKLabelArt1.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt1.setFont(font2)
        self.FKSliderArt1 = QSlider(self.frame_7)
        self.FKSliderArt1.setObjectName(u"FKSliderArt1")
        self.FKSliderArt1.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt1.setMinimum(-1800)
        self.FKSliderArt1.setMaximum(1800)
        self.FKSliderArt1.setSingleStep(10)
        self.FKSliderArt1.setPageStep(100)
        self.FKSliderArt1.setTracking(True)
        self.FKSliderArt1.setOrientation(Qt.Horizontal)
        self.FKSliderArt1.setInvertedAppearance(False)
        self.FKSliderArt1.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt1.setTickInterval(200)
        self.label_31 = QLabel(self.frame_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(278, 24, 16, 16))
        self.label_32 = QLabel(self.frame_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(132, 24, 31, 16))
        self.line_9 = QFrame(self.frame_7)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(105, 5, 20, 71))
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt1 = QDoubleSpinBox(self.frame_7)
        self.SpinBoxArt1.setObjectName(u"SpinBoxArt1")
        self.SpinBoxArt1.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt1.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt1.setDecimals(1)
        self.SpinBoxArt1.setMinimum(-180.000000000000000)
        self.SpinBoxArt1.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt1 = QPushButton(self.frame_7)
        self.FKInc10ButtonArt1.setObjectName(u"FKInc10ButtonArt1")
        self.FKInc10ButtonArt1.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt1 = QPushButton(self.frame_7)
        self.FKDec1ButtonArt1.setObjectName(u"FKDec1ButtonArt1")
        self.FKDec1ButtonArt1.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt1 = QPushButton(self.frame_7)
        self.FKDec0_1ButtonArt1.setObjectName(u"FKDec0_1ButtonArt1")
        self.FKDec0_1ButtonArt1.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt1 = QPushButton(self.frame_7)
        self.FKInc0_1ButtonArt1.setObjectName(u"FKInc0_1ButtonArt1")
        self.FKInc0_1ButtonArt1.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt1 = QPushButton(self.frame_7)
        self.FKInc1ButtonArt1.setObjectName(u"FKInc1ButtonArt1")
        self.FKInc1ButtonArt1.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt1 = QPushButton(self.frame_7)
        self.FKDec10ButtonArt1.setObjectName(u"FKDec10ButtonArt1")
        self.FKDec10ButtonArt1.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_2.addWidget(self.frame_7)

        self.FKGoButtonArt1 = QPushButton(self.layoutWidget)
        self.FKGoButtonArt1.setObjectName(u"FKGoButtonArt1")
        self.FKGoButtonArt1.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt1.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt1.setFont(font2)

        self.horizontalLayout_2.addWidget(self.FKGoButtonArt1)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(390, 110, 491, 81))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_8 = QFrame(self.layoutWidget1)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_33 = QLabel(self.frame_8)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(410, 24, 30, 16))
        self.FKLabelArt2 = QLabel(self.frame_8)
        self.FKLabelArt2.setObjectName(u"FKLabelArt2")
        self.FKLabelArt2.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt2.setFont(font2)
        self.FKSliderArt2 = QSlider(self.frame_8)
        self.FKSliderArt2.setObjectName(u"FKSliderArt2")
        self.FKSliderArt2.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt2.setMinimum(-900)
        self.FKSliderArt2.setMaximum(900)
        self.FKSliderArt2.setSingleStep(10)
        self.FKSliderArt2.setPageStep(100)
        self.FKSliderArt2.setTracking(True)
        self.FKSliderArt2.setOrientation(Qt.Horizontal)
        self.FKSliderArt2.setInvertedAppearance(False)
        self.FKSliderArt2.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt2.setTickInterval(200)
        self.label_35 = QLabel(self.frame_8)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(278, 24, 16, 16))
        self.label_36 = QLabel(self.frame_8)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(136, 24, 31, 16))
        self.line_10 = QFrame(self.frame_8)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(105, 5, 20, 71))
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt2 = QDoubleSpinBox(self.frame_8)
        self.SpinBoxArt2.setObjectName(u"SpinBoxArt2")
        self.SpinBoxArt2.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt2.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt2.setDecimals(1)
        self.SpinBoxArt2.setMinimum(-180.000000000000000)
        self.SpinBoxArt2.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt2 = QPushButton(self.frame_8)
        self.FKInc10ButtonArt2.setObjectName(u"FKInc10ButtonArt2")
        self.FKInc10ButtonArt2.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt2 = QPushButton(self.frame_8)
        self.FKDec1ButtonArt2.setObjectName(u"FKDec1ButtonArt2")
        self.FKDec1ButtonArt2.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt2 = QPushButton(self.frame_8)
        self.FKDec0_1ButtonArt2.setObjectName(u"FKDec0_1ButtonArt2")
        self.FKDec0_1ButtonArt2.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt2 = QPushButton(self.frame_8)
        self.FKInc0_1ButtonArt2.setObjectName(u"FKInc0_1ButtonArt2")
        self.FKInc0_1ButtonArt2.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt2 = QPushButton(self.frame_8)
        self.FKInc1ButtonArt2.setObjectName(u"FKInc1ButtonArt2")
        self.FKInc1ButtonArt2.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt2 = QPushButton(self.frame_8)
        self.FKDec10ButtonArt2.setObjectName(u"FKDec10ButtonArt2")
        self.FKDec10ButtonArt2.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_3.addWidget(self.frame_8)

        self.FKGoButtonArt2 = QPushButton(self.layoutWidget1)
        self.FKGoButtonArt2.setObjectName(u"FKGoButtonArt2")
        self.FKGoButtonArt2.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt2.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt2.setFont(font2)

        self.horizontalLayout_3.addWidget(self.FKGoButtonArt2)

        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(390, 190, 491, 81))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.frame_9 = QFrame(self.layoutWidget2)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.label_37 = QLabel(self.frame_9)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(410, 24, 30, 16))
        self.FKLabelArt3 = QLabel(self.frame_9)
        self.FKLabelArt3.setObjectName(u"FKLabelArt3")
        self.FKLabelArt3.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt3.setFont(font2)
        self.FKSliderArt3 = QSlider(self.frame_9)
        self.FKSliderArt3.setObjectName(u"FKSliderArt3")
        self.FKSliderArt3.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt3.setMinimum(-900)
        self.FKSliderArt3.setMaximum(900)
        self.FKSliderArt3.setSingleStep(10)
        self.FKSliderArt3.setPageStep(100)
        self.FKSliderArt3.setTracking(True)
        self.FKSliderArt3.setOrientation(Qt.Horizontal)
        self.FKSliderArt3.setInvertedAppearance(False)
        self.FKSliderArt3.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt3.setTickInterval(200)
        self.label_39 = QLabel(self.frame_9)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(278, 24, 16, 16))
        self.label_40 = QLabel(self.frame_9)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(136, 24, 30, 16))
        self.line_11 = QFrame(self.frame_9)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(105, 5, 20, 71))
        self.line_11.setFrameShape(QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt3 = QDoubleSpinBox(self.frame_9)
        self.SpinBoxArt3.setObjectName(u"SpinBoxArt3")
        self.SpinBoxArt3.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt3.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt3.setDecimals(1)
        self.SpinBoxArt3.setMinimum(-180.000000000000000)
        self.SpinBoxArt3.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt3 = QPushButton(self.frame_9)
        self.FKInc10ButtonArt3.setObjectName(u"FKInc10ButtonArt3")
        self.FKInc10ButtonArt3.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt3 = QPushButton(self.frame_9)
        self.FKDec1ButtonArt3.setObjectName(u"FKDec1ButtonArt3")
        self.FKDec1ButtonArt3.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt3 = QPushButton(self.frame_9)
        self.FKDec0_1ButtonArt3.setObjectName(u"FKDec0_1ButtonArt3")
        self.FKDec0_1ButtonArt3.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt3 = QPushButton(self.frame_9)
        self.FKInc0_1ButtonArt3.setObjectName(u"FKInc0_1ButtonArt3")
        self.FKInc0_1ButtonArt3.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt3 = QPushButton(self.frame_9)
        self.FKInc1ButtonArt3.setObjectName(u"FKInc1ButtonArt3")
        self.FKInc1ButtonArt3.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt3 = QPushButton(self.frame_9)
        self.FKDec10ButtonArt3.setObjectName(u"FKDec10ButtonArt3")
        self.FKDec10ButtonArt3.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_4.addWidget(self.frame_9)

        self.FKGoButtonArt3 = QPushButton(self.layoutWidget2)
        self.FKGoButtonArt3.setObjectName(u"FKGoButtonArt3")
        self.FKGoButtonArt3.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt3.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt3.setFont(font2)

        self.horizontalLayout_4.addWidget(self.FKGoButtonArt3)

        self.layoutWidget3 = QWidget(self.centralwidget)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(390, 270, 491, 81))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.frame_10 = QFrame(self.layoutWidget3)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.label_41 = QLabel(self.frame_10)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(408, 24, 31, 16))
        self.FKLabelArt4 = QLabel(self.frame_10)
        self.FKLabelArt4.setObjectName(u"FKLabelArt4")
        self.FKLabelArt4.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt4.setFont(font2)
        self.FKSliderArt4 = QSlider(self.frame_10)
        self.FKSliderArt4.setObjectName(u"FKSliderArt4")
        self.FKSliderArt4.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt4.setMinimum(-1800)
        self.FKSliderArt4.setMaximum(1800)
        self.FKSliderArt4.setSingleStep(10)
        self.FKSliderArt4.setPageStep(100)
        self.FKSliderArt4.setTracking(True)
        self.FKSliderArt4.setOrientation(Qt.Horizontal)
        self.FKSliderArt4.setInvertedAppearance(False)
        self.FKSliderArt4.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt4.setTickInterval(200)
        self.label_43 = QLabel(self.frame_10)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(278, 24, 16, 16))
        self.label_44 = QLabel(self.frame_10)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(132, 24, 31, 16))
        self.line_12 = QFrame(self.frame_10)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(105, 5, 20, 71))
        self.line_12.setFrameShape(QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt4 = QDoubleSpinBox(self.frame_10)
        self.SpinBoxArt4.setObjectName(u"SpinBoxArt4")
        self.SpinBoxArt4.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt4.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt4.setDecimals(1)
        self.SpinBoxArt4.setMinimum(-180.000000000000000)
        self.SpinBoxArt4.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt4 = QPushButton(self.frame_10)
        self.FKInc10ButtonArt4.setObjectName(u"FKInc10ButtonArt4")
        self.FKInc10ButtonArt4.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt4 = QPushButton(self.frame_10)
        self.FKDec1ButtonArt4.setObjectName(u"FKDec1ButtonArt4")
        self.FKDec1ButtonArt4.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt4 = QPushButton(self.frame_10)
        self.FKDec0_1ButtonArt4.setObjectName(u"FKDec0_1ButtonArt4")
        self.FKDec0_1ButtonArt4.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt4 = QPushButton(self.frame_10)
        self.FKInc0_1ButtonArt4.setObjectName(u"FKInc0_1ButtonArt4")
        self.FKInc0_1ButtonArt4.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt4 = QPushButton(self.frame_10)
        self.FKInc1ButtonArt4.setObjectName(u"FKInc1ButtonArt4")
        self.FKInc1ButtonArt4.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt4 = QPushButton(self.frame_10)
        self.FKDec10ButtonArt4.setObjectName(u"FKDec10ButtonArt4")
        self.FKDec10ButtonArt4.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_5.addWidget(self.frame_10)

        self.FKGoButtonArt4 = QPushButton(self.layoutWidget3)
        self.FKGoButtonArt4.setObjectName(u"FKGoButtonArt4")
        self.FKGoButtonArt4.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt4.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt4.setFont(font2)

        self.horizontalLayout_5.addWidget(self.FKGoButtonArt4)

        self.layoutWidget4 = QWidget(self.centralwidget)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(390, 350, 491, 81))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.frame_11 = QFrame(self.layoutWidget4)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.label_45 = QLabel(self.frame_11)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(410, 24, 30, 16))
        self.FKLabelArt5 = QLabel(self.frame_11)
        self.FKLabelArt5.setObjectName(u"FKLabelArt5")
        self.FKLabelArt5.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt5.setFont(font2)
        self.FKSliderArt5 = QSlider(self.frame_11)
        self.FKSliderArt5.setObjectName(u"FKSliderArt5")
        self.FKSliderArt5.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt5.setMinimum(-900)
        self.FKSliderArt5.setMaximum(900)
        self.FKSliderArt5.setSingleStep(10)
        self.FKSliderArt5.setPageStep(100)
        self.FKSliderArt5.setTracking(True)
        self.FKSliderArt5.setOrientation(Qt.Horizontal)
        self.FKSliderArt5.setInvertedAppearance(False)
        self.FKSliderArt5.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt5.setTickInterval(200)
        self.label_47 = QLabel(self.frame_11)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(278, 24, 16, 16))
        self.label_48 = QLabel(self.frame_11)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(136, 24, 30, 16))
        self.line_13 = QFrame(self.frame_11)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(105, 5, 20, 71))
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt5 = QDoubleSpinBox(self.frame_11)
        self.SpinBoxArt5.setObjectName(u"SpinBoxArt5")
        self.SpinBoxArt5.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt5.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt5.setDecimals(1)
        self.SpinBoxArt5.setMinimum(-180.000000000000000)
        self.SpinBoxArt5.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt5 = QPushButton(self.frame_11)
        self.FKInc10ButtonArt5.setObjectName(u"FKInc10ButtonArt5")
        self.FKInc10ButtonArt5.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt5 = QPushButton(self.frame_11)
        self.FKDec1ButtonArt5.setObjectName(u"FKDec1ButtonArt5")
        self.FKDec1ButtonArt5.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt5 = QPushButton(self.frame_11)
        self.FKDec0_1ButtonArt5.setObjectName(u"FKDec0_1ButtonArt5")
        self.FKDec0_1ButtonArt5.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt5 = QPushButton(self.frame_11)
        self.FKInc0_1ButtonArt5.setObjectName(u"FKInc0_1ButtonArt5")
        self.FKInc0_1ButtonArt5.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt5 = QPushButton(self.frame_11)
        self.FKInc1ButtonArt5.setObjectName(u"FKInc1ButtonArt5")
        self.FKInc1ButtonArt5.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt5 = QPushButton(self.frame_11)
        self.FKDec10ButtonArt5.setObjectName(u"FKDec10ButtonArt5")
        self.FKDec10ButtonArt5.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_6.addWidget(self.frame_11)

        self.FKGoButtonArt5 = QPushButton(self.layoutWidget4)
        self.FKGoButtonArt5.setObjectName(u"FKGoButtonArt5")
        self.FKGoButtonArt5.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt5.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt5.setFont(font2)

        self.horizontalLayout_6.addWidget(self.FKGoButtonArt5)

        self.layoutWidget5 = QWidget(self.centralwidget)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(390, 430, 491, 81))
        self.horizontalLayout_8 = QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.frame_12 = QFrame(self.layoutWidget5)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.label_49 = QLabel(self.frame_12)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(408, 24, 31, 16))
        self.FKLabelArt6 = QLabel(self.frame_12)
        self.FKLabelArt6.setObjectName(u"FKLabelArt6")
        self.FKLabelArt6.setGeometry(QRect(10, 10, 101, 20))
        self.FKLabelArt6.setFont(font2)
        self.FKSliderArt6 = QSlider(self.frame_12)
        self.FKSliderArt6.setObjectName(u"FKSliderArt6")
        self.FKSliderArt6.setGeometry(QRect(140, 4, 281, 22))
        self.FKSliderArt6.setMinimum(-1800)
        self.FKSliderArt6.setMaximum(1800)
        self.FKSliderArt6.setSingleStep(10)
        self.FKSliderArt6.setPageStep(100)
        self.FKSliderArt6.setTracking(True)
        self.FKSliderArt6.setOrientation(Qt.Horizontal)
        self.FKSliderArt6.setInvertedAppearance(False)
        self.FKSliderArt6.setTickPosition(QSlider.TicksBelow)
        self.FKSliderArt6.setTickInterval(200)
        self.label_51 = QLabel(self.frame_12)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(278, 24, 16, 16))
        self.label_52 = QLabel(self.frame_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(132, 24, 31, 16))
        self.line_14 = QFrame(self.frame_12)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(105, 5, 20, 71))
        self.line_14.setFrameShape(QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.SpinBoxArt6 = QDoubleSpinBox(self.frame_12)
        self.SpinBoxArt6.setObjectName(u"SpinBoxArt6")
        self.SpinBoxArt6.setGeometry(QRect(25, 40, 62, 22))
        self.SpinBoxArt6.setAlignment(Qt.AlignCenter)
        self.SpinBoxArt6.setDecimals(1)
        self.SpinBoxArt6.setMinimum(-180.000000000000000)
        self.SpinBoxArt6.setMaximum(180.000000000000000)
        self.FKInc10ButtonArt6 = QPushButton(self.frame_12)
        self.FKInc10ButtonArt6.setObjectName(u"FKInc10ButtonArt6")
        self.FKInc10ButtonArt6.setGeometry(QRect(385, 50, 41, 23))
        self.FKDec1ButtonArt6 = QPushButton(self.frame_12)
        self.FKDec1ButtonArt6.setObjectName(u"FKDec1ButtonArt6")
        self.FKDec1ButtonArt6.setGeometry(QRect(185, 50, 41, 23))
        self.FKDec0_1ButtonArt6 = QPushButton(self.frame_12)
        self.FKDec0_1ButtonArt6.setObjectName(u"FKDec0_1ButtonArt6")
        self.FKDec0_1ButtonArt6.setGeometry(QRect(235, 50, 41, 23))
        self.FKInc0_1ButtonArt6 = QPushButton(self.frame_12)
        self.FKInc0_1ButtonArt6.setObjectName(u"FKInc0_1ButtonArt6")
        self.FKInc0_1ButtonArt6.setGeometry(QRect(285, 50, 41, 23))
        self.FKInc1ButtonArt6 = QPushButton(self.frame_12)
        self.FKInc1ButtonArt6.setObjectName(u"FKInc1ButtonArt6")
        self.FKInc1ButtonArt6.setGeometry(QRect(335, 50, 41, 23))
        self.FKDec10ButtonArt6 = QPushButton(self.frame_12)
        self.FKDec10ButtonArt6.setObjectName(u"FKDec10ButtonArt6")
        self.FKDec10ButtonArt6.setGeometry(QRect(135, 50, 41, 23))

        self.horizontalLayout_8.addWidget(self.frame_12)

        self.FKGoButtonArt6 = QPushButton(self.layoutWidget5)
        self.FKGoButtonArt6.setObjectName(u"FKGoButtonArt6")
        self.FKGoButtonArt6.setMinimumSize(QSize(35, 30))
        self.FKGoButtonArt6.setMaximumSize(QSize(35, 30))
        self.FKGoButtonArt6.setFont(font2)

        self.horizontalLayout_8.addWidget(self.FKGoButtonArt6)

        self.IkDecButtonZ = QPushButton(self.centralwidget)
        self.IkDecButtonZ.setObjectName(u"IkDecButtonZ")
        self.IkDecButtonZ.setEnabled(False)
        self.IkDecButtonZ.setGeometry(QRect(40, 435, 50, 50))
        self.IkDecButtonZ.setMinimumSize(QSize(50, 50))
        self.IkDecButtonZ.setMaximumSize(QSize(50, 50))
        self.IkIncButtonZ = QPushButton(self.centralwidget)
        self.IkIncButtonZ.setObjectName(u"IkIncButtonZ")
        self.IkIncButtonZ.setEnabled(False)
        self.IkIncButtonZ.setGeometry(QRect(40, 360, 50, 50))
        self.IkIncButtonZ.setMinimumSize(QSize(50, 50))
        self.IkIncButtonZ.setMaximumSize(QSize(50, 50))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(280, 340, 91, 166))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.IkMultiplierDecSpinBox = QPushButton(self.frame_3)
        self.IkMultiplierDecSpinBox.setObjectName(u"IkMultiplierDecSpinBox")
        self.IkMultiplierDecSpinBox.setEnabled(False)
        self.IkMultiplierDecSpinBox.setGeometry(QRect(43, 110, 31, 23))
        self.IkMultiplierDiv10SpinBox = QPushButton(self.frame_3)
        self.IkMultiplierDiv10SpinBox.setObjectName(u"IkMultiplierDiv10SpinBox")
        self.IkMultiplierDiv10SpinBox.setEnabled(False)
        self.IkMultiplierDiv10SpinBox.setGeometry(QRect(3, 110, 41, 23))
        self.IkMultiplierIncSpinBox = QPushButton(self.frame_3)
        self.IkMultiplierIncSpinBox.setObjectName(u"IkMultiplierIncSpinBox")
        self.IkMultiplierIncSpinBox.setEnabled(False)
        self.IkMultiplierIncSpinBox.setGeometry(QRect(43, 40, 31, 23))
        self.IkMultiplierX10SpinBox = QPushButton(self.frame_3)
        self.IkMultiplierX10SpinBox.setObjectName(u"IkMultiplierX10SpinBox")
        self.IkMultiplierX10SpinBox.setEnabled(False)
        self.IkMultiplierX10SpinBox.setGeometry(QRect(3, 40, 41, 23))
        self.IkMultiplierSpinBox = QDoubleSpinBox(self.frame_3)
        self.IkMultiplierSpinBox.setObjectName(u"IkMultiplierSpinBox")
        self.IkMultiplierSpinBox.setEnabled(False)
        self.IkMultiplierSpinBox.setGeometry(QRect(3, 75, 71, 22))
        self.IkMultiplierSpinBox.setAlignment(Qt.AlignCenter)
        self.IkMultiplierSpinBox.setDecimals(1)
        self.IkMultiplierSpinBox.setMinimum(0.000000000000000)
        self.IkMultiplierSpinBox.setMaximum(100.000000000000000)
        self.layoutWidget6 = QWidget(self.centralwidget)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(121, 341, 152, 164))
        self.gridLayout = QGridLayout(self.layoutWidget6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.IkIncButtonY = QPushButton(self.layoutWidget6)
        self.IkIncButtonY.setObjectName(u"IkIncButtonY")
        self.IkIncButtonY.setEnabled(False)
        self.IkIncButtonY.setMinimumSize(QSize(50, 50))
        self.IkIncButtonY.setMaximumSize(QSize(50, 50))

        self.gridLayout.addWidget(self.IkIncButtonY, 1, 2, 1, 1)

        self.IkDecButtonY = QPushButton(self.layoutWidget6)
        self.IkDecButtonY.setObjectName(u"IkDecButtonY")
        self.IkDecButtonY.setEnabled(False)
        self.IkDecButtonY.setMinimumSize(QSize(50, 50))
        self.IkDecButtonY.setMaximumSize(QSize(50, 50))

        self.gridLayout.addWidget(self.IkDecButtonY, 1, 0, 1, 1)

        self.IkIncButtonX = QPushButton(self.layoutWidget6)
        self.IkIncButtonX.setObjectName(u"IkIncButtonX")
        self.IkIncButtonX.setEnabled(False)
        self.IkIncButtonX.setMinimumSize(QSize(50, 50))
        self.IkIncButtonX.setMaximumSize(QSize(50, 50))

        self.gridLayout.addWidget(self.IkIncButtonX, 0, 1, 1, 1)

        self.IkDecButtonX = QPushButton(self.layoutWidget6)
        self.IkDecButtonX.setObjectName(u"IkDecButtonX")
        self.IkDecButtonX.setEnabled(False)
        self.IkDecButtonX.setMinimumSize(QSize(50, 50))
        self.IkDecButtonX.setMaximumSize(QSize(50, 50))

        self.gridLayout.addWidget(self.IkDecButtonX, 2, 1, 1, 1)

        self.G0MoveRadioButton = QRadioButton(self.centralwidget)
        self.G0MoveRadioButton.setObjectName(u"G0MoveRadioButton")
        self.G0MoveRadioButton.setGeometry(QRect(29, 170, 82, 17))
        self.G0MoveRadioButton.setChecked(True)
        self.G1MoveRadioButton = QRadioButton(self.centralwidget)
        self.G1MoveRadioButton.setObjectName(u"G1MoveRadioButton")
        self.G1MoveRadioButton.setGeometry(QRect(99, 170, 82, 17))
        self.FeedRateLabel = QLabel(self.centralwidget)
        self.FeedRateLabel.setObjectName(u"FeedRateLabel")
        self.FeedRateLabel.setEnabled(False)
        self.FeedRateLabel.setGeometry(QRect(200, 170, 51, 16))
        self.FeedRateInput = QDoubleSpinBox(self.centralwidget)
        self.FeedRateInput.setObjectName(u"FeedRateInput")
        self.FeedRateInput.setEnabled(False)
        self.FeedRateInput.setGeometry(QRect(255, 167, 95, 22))
        self.FeedRateInput.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.FeedRateInput.setDecimals(0)
        self.FeedRateInput.setMinimum(0.000000000000000)
        self.FeedRateInput.setMaximum(100000.000000000000000)
        self.FeedRateInput.setSingleStep(100.000000000000000)
        self.FeedRateInput.setValue(500.000000000000000)
        MainWindow.setCentralWidget(self.centralwidget)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_15.raise_()
        self.KillAlarmLockButton.raise_()
        self.HomeButton.raise_()
        self.ZeroPositionButton.raise_()
        self.InverseKinematicsLabel.raise_()
        self.label_54.raise_()
        self.IkOutputValueFrame.raise_()
        self.line_16.raise_()
        self.ConsoleInput.raise_()
        self.ConsoleButtonSend.raise_()
        self.ConsoleShowOkRespcheckBox.raise_()
        self.ConsoleLabel.raise_()
        self.ConsoleOutput.raise_()
        self.line_17.raise_()
        self.GripperFrame.raise_()
        self.frame_4.raise_()
        self.SerialPortLabel.raise_()
        self.RobotStateLabel.raise_()
        self.SerialPortComboBox.raise_()
        self.ConnectButton.raise_()
        self.SerialPortRefreshButton.raise_()
        self.RobotStateDisplay.raise_()
        self.BaudRateComboBox.raise_()
        self.BaudRateLabel.raise_()
        self.ConsoleShowVerbosecheckBox.raise_()
        self.FKGoAllButton.raise_()
        self.FKOutputValueFrame.raise_()
        self.IkDecButtonZ.raise_()
        self.IkIncButtonZ.raise_()
        self.frame_3.raise_()
        self.G0MoveRadioButton.raise_()
        self.G1MoveRadioButton.raise_()
        self.FeedRateLabel.raise_()
        self.FeedRateInput.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 21))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.SerialPortComboBox, self.SerialPortRefreshButton)
        QWidget.setTabOrder(self.SerialPortRefreshButton, self.BaudRateComboBox)
        QWidget.setTabOrder(self.BaudRateComboBox, self.ConnectButton)
        QWidget.setTabOrder(self.ConnectButton, self.HomeButton)
        QWidget.setTabOrder(self.HomeButton, self.KillAlarmLockButton)
        QWidget.setTabOrder(self.KillAlarmLockButton, self.ZeroPositionButton)
        QWidget.setTabOrder(self.ZeroPositionButton, self.SpinBoxArt1)
        QWidget.setTabOrder(self.SpinBoxArt1, self.FKGoButtonArt1)
        QWidget.setTabOrder(self.FKGoButtonArt1, self.SpinBoxArt2)
        QWidget.setTabOrder(self.SpinBoxArt2, self.FKGoButtonArt2)
        QWidget.setTabOrder(self.FKGoButtonArt2, self.SpinBoxArt3)
        QWidget.setTabOrder(self.SpinBoxArt3, self.FKGoButtonArt3)
        QWidget.setTabOrder(self.FKGoButtonArt3, self.SpinBoxArt4)
        QWidget.setTabOrder(self.SpinBoxArt4, self.FKGoButtonArt4)
        QWidget.setTabOrder(self.FKGoButtonArt4, self.SpinBoxArt5)
        QWidget.setTabOrder(self.SpinBoxArt5, self.FKGoButtonArt5)
        QWidget.setTabOrder(self.FKGoButtonArt5, self.SpinBoxArt6)
        QWidget.setTabOrder(self.SpinBoxArt6, self.FKGoButtonArt6)
        QWidget.setTabOrder(self.FKGoButtonArt6, self.G0MoveRadioButton)
        QWidget.setTabOrder(self.G0MoveRadioButton, self.G1MoveRadioButton)
        QWidget.setTabOrder(self.G1MoveRadioButton, self.FKGoAllButton)
        QWidget.setTabOrder(self.FKGoAllButton, self.ConsoleInput)
        QWidget.setTabOrder(self.ConsoleInput, self.ConsoleButtonSend)
        QWidget.setTabOrder(self.ConsoleButtonSend, self.ConsoleShowVerbosecheckBox)
        QWidget.setTabOrder(self.ConsoleShowVerbosecheckBox, self.ConsoleShowOkRespcheckBox)
        QWidget.setTabOrder(self.ConsoleShowOkRespcheckBox, self.Inc10ButtonGripper)
        QWidget.setTabOrder(self.Inc10ButtonGripper, self.Inc1ButtonGripper)
        QWidget.setTabOrder(self.Inc1ButtonGripper, self.SpinBoxGripper)
        QWidget.setTabOrder(self.SpinBoxGripper, self.IKInputSpinBoxZ)
        QWidget.setTabOrder(self.IKInputSpinBoxZ, self.FKInc10ButtonArt2)
        QWidget.setTabOrder(self.FKInc10ButtonArt2, self.FKDec1ButtonArt2)
        QWidget.setTabOrder(self.FKDec1ButtonArt2, self.Dec1ButtonGripper)
        QWidget.setTabOrder(self.Dec1ButtonGripper, self.ConsoleOutput)
        QWidget.setTabOrder(self.ConsoleOutput, self.FKDec10ButtonArt2)
        QWidget.setTabOrder(self.FKDec10ButtonArt2, self.FKInc1ButtonArt2)
        QWidget.setTabOrder(self.FKInc1ButtonArt2, self.Dec10ButtonGripper)
        QWidget.setTabOrder(self.Dec10ButtonGripper, self.FKInc1ButtonArt1)
        QWidget.setTabOrder(self.FKInc1ButtonArt1, self.IKInputSpinBoxY)
        QWidget.setTabOrder(self.IKInputSpinBoxY, self.FKSliderArt3)
        QWidget.setTabOrder(self.FKSliderArt3, self.FKDec10ButtonArt1)
        QWidget.setTabOrder(self.FKDec10ButtonArt1, self.FKInc10ButtonArt3)
        QWidget.setTabOrder(self.FKInc10ButtonArt3, self.FKDec1ButtonArt3)
        QWidget.setTabOrder(self.FKDec1ButtonArt3, self.FKDec0_1ButtonArt3)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt3, self.FKInc0_1ButtonArt3)
        QWidget.setTabOrder(self.FKInc0_1ButtonArt3, self.FKInc1ButtonArt3)
        QWidget.setTabOrder(self.FKInc1ButtonArt3, self.FKDec10ButtonArt3)
        QWidget.setTabOrder(self.FKDec10ButtonArt3, self.FKInc0_1ButtonArt1)
        QWidget.setTabOrder(self.FKInc0_1ButtonArt1, self.FKSliderArt4)
        QWidget.setTabOrder(self.FKSliderArt4, self.FKDec1ButtonArt1)
        QWidget.setTabOrder(self.FKDec1ButtonArt1, self.FKInc10ButtonArt4)
        QWidget.setTabOrder(self.FKInc10ButtonArt4, self.FKDec1ButtonArt4)
        QWidget.setTabOrder(self.FKDec1ButtonArt4, self.FKDec0_1ButtonArt4)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt4, self.FKInc0_1ButtonArt4)
        QWidget.setTabOrder(self.FKInc0_1ButtonArt4, self.FKInc1ButtonArt4)
        QWidget.setTabOrder(self.FKInc1ButtonArt4, self.FKDec10ButtonArt4)
        QWidget.setTabOrder(self.FKDec10ButtonArt4, self.FKInc10ButtonArt1)
        QWidget.setTabOrder(self.FKInc10ButtonArt1, self.FKSliderArt5)
        QWidget.setTabOrder(self.FKSliderArt5, self.FKDec0_1ButtonArt1)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt1, self.FKInc10ButtonArt5)
        QWidget.setTabOrder(self.FKInc10ButtonArt5, self.FKDec1ButtonArt5)
        QWidget.setTabOrder(self.FKDec1ButtonArt5, self.FKDec0_1ButtonArt5)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt5, self.FKInc0_1ButtonArt5)
        QWidget.setTabOrder(self.FKInc0_1ButtonArt5, self.FKInc1ButtonArt5)
        QWidget.setTabOrder(self.FKInc1ButtonArt5, self.FKDec10ButtonArt5)
        QWidget.setTabOrder(self.FKDec10ButtonArt5, self.FKSliderArt1)
        QWidget.setTabOrder(self.FKSliderArt1, self.FKSliderArt6)
        QWidget.setTabOrder(self.FKSliderArt6, self.FKSliderArt2)
        QWidget.setTabOrder(self.FKSliderArt2, self.FKInc10ButtonArt6)
        QWidget.setTabOrder(self.FKInc10ButtonArt6, self.FKDec1ButtonArt6)
        QWidget.setTabOrder(self.FKDec1ButtonArt6, self.FKDec0_1ButtonArt6)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt6, self.FKInc0_1ButtonArt6)
        QWidget.setTabOrder(self.FKInc0_1ButtonArt6, self.FKInc1ButtonArt6)
        QWidget.setTabOrder(self.FKInc1ButtonArt6, self.FKDec10ButtonArt6)
        QWidget.setTabOrder(self.FKDec10ButtonArt6, self.SliderGripper)
        QWidget.setTabOrder(self.SliderGripper, self.IkDecButtonZ)
        QWidget.setTabOrder(self.IkDecButtonZ, self.IkIncButtonZ)
        QWidget.setTabOrder(self.IkIncButtonZ, self.IkMultiplierDecSpinBox)
        QWidget.setTabOrder(self.IkMultiplierDecSpinBox, self.IkMultiplierDiv10SpinBox)
        QWidget.setTabOrder(self.IkMultiplierDiv10SpinBox, self.IkMultiplierIncSpinBox)
        QWidget.setTabOrder(self.IkMultiplierIncSpinBox, self.IkMultiplierX10SpinBox)
        QWidget.setTabOrder(self.IkMultiplierX10SpinBox, self.IkMultiplierSpinBox)
        QWidget.setTabOrder(self.IkMultiplierSpinBox, self.IkIncButtonY)
        QWidget.setTabOrder(self.IkIncButtonY, self.IkDecButtonY)
        QWidget.setTabOrder(self.IkDecButtonY, self.IkIncButtonX)
        QWidget.setTabOrder(self.IkIncButtonX, self.IkDecButtonX)
        QWidget.setTabOrder(self.IkDecButtonX, self.IKInputSpinBoxX)
        QWidget.setTabOrder(self.IKInputSpinBoxX, self.FKDec0_1ButtonArt2)
        QWidget.setTabOrder(self.FKDec0_1ButtonArt2, self.FKInc0_1ButtonArt2)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuMenu.addAction(self.actionPreferences)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Asgard", None))
        self.actionManual.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About ...", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.KillAlarmLockButton.setText(QCoreApplication.translate("MainWindow", u"Kill Alarm Lock", None))
        self.HomeButton.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.ZeroPositionButton.setText(QCoreApplication.translate("MainWindow", u"Zero position", None))
        self.InverseKinematicsLabel.setText(QCoreApplication.translate("MainWindow", u"Inverse Kinematics", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Forward Kinematics", None))
        self.IkOutputValueZ.setText(QCoreApplication.translate("MainWindow", u"200 mm", None))
        self.IkLabelOutputY.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.IkOutputValueX.setText(QCoreApplication.translate("MainWindow", u"200 mm", None))
        self.IkLabelOutputZ.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.IkLabelOutputX.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.IkOutputValueY.setText(QCoreApplication.translate("MainWindow", u"200 mm", None))
        self.ConsoleButtonSend.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.ConsoleShowOkRespcheckBox.setText(QCoreApplication.translate("MainWindow", u"Show 'ok' Responses", None))
        self.ConsoleLabel.setText(QCoreApplication.translate("MainWindow", u"Console", None))
        self.ConsoleOutput.setPlainText("")
        self.GripperLabel.setText(QCoreApplication.translate("MainWindow", u"Gripper", None))
        self.Dec1ButtonGripper.setText(QCoreApplication.translate("MainWindow", u"-1%", None))
        self.Dec10ButtonGripper.setText(QCoreApplication.translate("MainWindow", u"-10%", None))
        self.SpinBoxGripper.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.Gripper0Label.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.Gripper100Label.setText(QCoreApplication.translate("MainWindow", u"100%", None))
        self.Inc10ButtonGripper.setText(QCoreApplication.translate("MainWindow", u"+10%", None))
        self.Inc1ButtonGripper.setText(QCoreApplication.translate("MainWindow", u"+1%", None))
        self.GoButtonGripper.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.IKInputSpinBoxX.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.IKInputSpinBoxY.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.IkLabelInputY.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.IkLabelInputX.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.IKInputSpinBoxZ.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.IkLabelInputZ.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.SerialPortLabel.setText(QCoreApplication.translate("MainWindow", u"Serial Port:", None))
        self.RobotStateLabel.setText(QCoreApplication.translate("MainWindow", u"State:", None))
        self.ConnectButton.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.SerialPortRefreshButton.setText(QCoreApplication.translate("MainWindow", u"\u21ba", None))
        self.RobotStateDisplay.setText(QCoreApplication.translate("MainWindow", u"Disconnected", None))
        self.BaudRateComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"115200", None))
        self.BaudRateComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"57600", None))
        self.BaudRateComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"38400", None))
        self.BaudRateComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"28800", None))
        self.BaudRateComboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"19200", None))
        self.BaudRateComboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"14400", None))
        self.BaudRateComboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"9600", None))
        self.BaudRateComboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"4800", None))
        self.BaudRateComboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"2400", None))
        self.BaudRateComboBox.setItemText(9, QCoreApplication.translate("MainWindow", u"1200", None))
        self.BaudRateComboBox.setItemText(10, QCoreApplication.translate("MainWindow", u"600", None))
        self.BaudRateComboBox.setItemText(11, QCoreApplication.translate("MainWindow", u"300", None))

        self.BaudRateComboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"115200", None))
        self.BaudRateLabel.setText(QCoreApplication.translate("MainWindow", u"Baud Rate:", None))
        self.ConsoleShowVerbosecheckBox.setText(QCoreApplication.translate("MainWindow", u"Show Verbose Output", None))
        self.FKGoAllButton.setText(QCoreApplication.translate("MainWindow", u"Go All!", None))
        self.FKCurrentPosValueArt1.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKLabelCurrentPosArt1.setText(QCoreApplication.translate("MainWindow", u"Art1:", None))
        self.FKLabelCurrentPosArt2.setText(QCoreApplication.translate("MainWindow", u"Art2:", None))
        self.FKCurrentPosValueArt2.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKLabelCurrentPosArt3.setText(QCoreApplication.translate("MainWindow", u"Art3:", None))
        self.FKCurrentPosValueArt3.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKLabelCurrentPosArt4.setText(QCoreApplication.translate("MainWindow", u"Art4:", None))
        self.FKCurrentPosValueArt4.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKLabelCurrentPosArt5.setText(QCoreApplication.translate("MainWindow", u"Art5:", None))
        self.FKCurrentPosValueArt5.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKCurrentPosValueArt6.setText(QCoreApplication.translate("MainWindow", u"0,0\u00ba", None))
        self.FKLabelCurrentPosArt6.setText(QCoreApplication.translate("MainWindow", u"Art6:", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"180\u00ba", None))
        self.FKLabelArt1.setText(QCoreApplication.translate("MainWindow", u"Articulation 1", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"-180\u00ba", None))
        self.SpinBoxArt1.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt1.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt1.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"90\u00ba", None))
        self.FKLabelArt2.setText(QCoreApplication.translate("MainWindow", u"Articulation 2", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"-90\u00ba", None))
        self.SpinBoxArt2.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt2.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt2.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"90\u00ba", None))
        self.FKLabelArt3.setText(QCoreApplication.translate("MainWindow", u"Articulation 3", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"-90\u00ba", None))
        self.SpinBoxArt3.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt3.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt3.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"180\u00ba", None))
        self.FKLabelArt4.setText(QCoreApplication.translate("MainWindow", u"Articulation 4", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"-180\u00ba", None))
        self.SpinBoxArt4.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt4.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt4.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"90\u00ba", None))
        self.FKLabelArt5.setText(QCoreApplication.translate("MainWindow", u"Articulation 5", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"-90\u00ba", None))
        self.SpinBoxArt5.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt5.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt5.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"180\u00ba", None))
        self.FKLabelArt6.setText(QCoreApplication.translate("MainWindow", u"Articulation 6", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"0\u00ba", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"-180\u00ba", None))
        self.SpinBoxArt6.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.FKInc10ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"+10\u00ba", None))
        self.FKDec1ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"-1\u00ba", None))
        self.FKDec0_1ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"-0,1\u00ba", None))
        self.FKInc0_1ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"+0,1\u00ba", None))
        self.FKInc1ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"+1\u00ba", None))
        self.FKDec10ButtonArt6.setText(QCoreApplication.translate("MainWindow", u"-10\u00ba", None))
        self.FKGoButtonArt6.setText(QCoreApplication.translate("MainWindow", u"Go!", None))
        self.IkDecButtonZ.setText(QCoreApplication.translate("MainWindow", u"Z-", None))
        self.IkIncButtonZ.setText(QCoreApplication.translate("MainWindow", u"Z+", None))
        self.IkMultiplierDecSpinBox.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.IkMultiplierDiv10SpinBox.setText(QCoreApplication.translate("MainWindow", u"\u00f710", None))
        self.IkMultiplierIncSpinBox.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.IkMultiplierX10SpinBox.setText(QCoreApplication.translate("MainWindow", u"\u00d710", None))
        self.IkMultiplierSpinBox.setSuffix("")
        self.IkIncButtonY.setText(QCoreApplication.translate("MainWindow", u"Y+", None))
        self.IkDecButtonY.setText(QCoreApplication.translate("MainWindow", u"Y-", None))
        self.IkIncButtonX.setText(QCoreApplication.translate("MainWindow", u"X+", None))
        self.IkDecButtonX.setText(QCoreApplication.translate("MainWindow", u"X-", None))
        self.G0MoveRadioButton.setText(QCoreApplication.translate("MainWindow", u"G0 Move", None))
        self.G1MoveRadioButton.setText(QCoreApplication.translate("MainWindow", u"G01 Move", None))
        self.FeedRateLabel.setText(QCoreApplication.translate("MainWindow", u"Feed Rate", None))
        self.FeedRateInput.setSuffix(QCoreApplication.translate("MainWindow", u" \u00ba/min", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

